	.FILE "imgtbl.asm"
	.OPTION B,D,L,T

	.include imgtbl.glo
	.DATA
	.even

	.include plyrpbck.glo

	.include swpuseq.glo

	.include cowering.glo

	.include crowd2.glo

	.include storm.glo

	.include dcs.glo

	.include lighten.glo

	.include newheads.glo

	.include newmugs.glo

	.include XXXHD.GLO

	.include UGROUND.GLO

	.include shatter.glo

	.include hoop2.glo

	.include names3.glo
