// LOADW_1481.c
// Generated by decompiling LOADW.EXE
// using Reko decompiler version 0.12.2.0.

#include "LOADW.h"

// 1481:0004: void fn1481_0004(Register Eq_14 ds, Stack Eq_14 wArg04, Stack Eq_14 wArg06)
// Called from:
//      fn0800_0D60
//      fn0800_7DD1
//      fn0800_8095
void fn1481_0004(Eq_14 ds, Eq_14 wArg04, Eq_14 wArg06)
{
	if (Mem7[ds:0x38C0:word16] == 0x00)
	{
		__out<word16>(Mem7[ds:0x3AC6:word16], wArg04);
		__out<word16>(Mem7[ds:15044:word16], wArg06);
	}
	else
	{
		selector es_26 = Mem25[ds:0x38C0:selector];
		Mem28[es_26:Mem25[ds:0x3AC6:word16] + 0x00:word16] = wArg04;
		Mem31[es_26:Mem28[ds:15044:word16] + 0x00:word16] = wArg06;
	}
}

