// LOADW_1484.c
// Generated by decompiling LOADW.EXE
// using Reko decompiler version 0.12.2.0.

#include "LOADW.h"

// 1484:000E: Register Eq_14 fn1484_000E(Register Eq_14 ds, Stack Eq_14 wArg04, Stack Eq_14 wArg06, Stack Eq_14 wArg08, Register out Eq_14 dsOut)
// Called from:
//      main
Eq_14 fn1484_000E(Eq_14 ds, Eq_14 wArg04, Eq_14 wArg06, Eq_14 wArg08, union Eq_14 & dsOut)
{
	mp16 fp;
	Eq_14 wLoc06;
	Eq_14 wLoc04;
	word16 ax_239;
	word16 si_240;
	word16 di_241;
	Eq_14 ds_120;
	fn149A_02C8(0x06, ds, wLoc06, wLoc04, out ax_239, out si_240, out di_241, out ds_120);
	Mem25[ds_120:0x38C0:word16] = 0xC000;
	Mem26[ds_120:15050:word16] = 0x7D00;
	Mem27[ds_120:0x3AC8:word16] = 0x7D01;
	Mem28[ds_120:0x3AC6:word16] = 0x7E00;
	Mem29[ds_120:15044:word16] = 0x7F00;
	Mem30[ds_120:0x38C2:word16] = 0x7000;
	union Eq_14 Eq_14::* bp_133 = fp - 2;
	Eq_14 sp_20;
	sp_20.u0 = <invalid>;
	Eq_14 ss;
	if ((wArg06 | wArg04) != 0x00)
	{
		ss->*((word32) sp_20 - 2) = ss;
		ss->*((word32) sp_20 - 4) = fp - 6;
		ss->*((word32) sp_20 - 6) = ds_120;
		(ss->*((word32) sp_20 - 8)).u0 = 0x310E;
		ss->*((word32) sp_20 - 0x0A) = wArg06;
		ss->*((word32) sp_20 - 0x0C) = wArg04;
		if (fn149A_2876(ds_120, ss->*((word32) sp_20 - 0x0C), ss->*((word32) sp_20 - 8), out ds_120) != 0x00)
		{
			Mem71[ds_120:0x38C0:word16] = wLoc04;
			if (wLoc04 == 0x00)
			{
				Mem93[ds_120:0x38C2:word16] = wLoc06;
				Mem98[ds_120:15050:word16] = SEQ(SLICE(wLoc06, byte, 8) + 0x10, SLICE(wLoc06, byte, 0));
				Mem101[ds_120:0x3AC8:word16] = wLoc06 + 0x1001;
				Mem107[ds_120:0x3AC6:word16] = SEQ(SLICE(wLoc06, byte, 8) + 0x20, SLICE(wLoc06, byte, 0));
				Mem114[ds_120:15044:word16] = SEQ(SLICE(wLoc06, byte, 8) + 0x30, SLICE(wLoc06, byte, 0));
			}
			else
			{
				word16 ax_78 = wLoc06 - Mem71[ds_120:0x38C2:word16];
				Mem81[ds_120:0x38C2:word16] = Mem79[ds_120:0x38C2:word16] + ax_78;
				Mem83[ds_120:15044:word16] = Mem81[ds_120:15044:word16] + ax_78;
				Mem85[ds_120:0x3AC6:word16] = Mem83[ds_120:0x3AC6:word16] + ax_78;
				Mem87[ds_120:0x3AC8:word16] = Mem85[ds_120:0x3AC8:word16] + ax_78;
				Mem89[ds_120:15050:word16] = Mem87[ds_120:15050:word16] + ax_78;
			}
		}
	}
	if (wArg08 != 0x00)
	{
		if (Mem117[ds_120:0x38C0:word16] != 0x00)
		{
			Mem154[ss:sp_20 + -2:word16] = Mem117[ds_120:0x38C2:word16];
			Mem157[ss:sp_20 + -4:word16] = Mem154[ds_120:0x38C0:word16];
			ss->*((word32) sp_20 - 6) = ds_120;
			(ss->*((word32) sp_20 - 8)).u0 = 0x3112;
			union Eq_14 Eq_14::* bp_163;
			word16 si_243;
			Eq_14 ds_166;
			fn149A_0ABC(ds_120, ss->*((word32) sp_20 - 8), out bp_163, out si_243, out ds_166);
			Eq_14 bp_179;
			bp_179.u1 = (ss->*bp_163).u1;
			dsOut = ds_166;
			return bp_179;
		}
		Mem126[ss:sp_20 + -2:word16] = Mem117[ds_120:0x38C2:word16];
		ss->*((word32) sp_20 - 4) = ds_120;
		(ss->*((word32) sp_20 - 6)).u0 = 0x313D;
		word16 si_242;
		fn149A_0ABC(ds_120, ss->*((word32) sp_20 - 6), out bp_133, out si_242, out ds_120);
	}
	Eq_14 bp_150;
	bp_150.u1 = (ss->*bp_133).u1;
	dsOut = ds_120;
	return bp_150;
}

