// LOADW_1496.c
// Generated by decompiling LOADW.EXE
// using Reko decompiler version 0.12.2.0.

#include "LOADW.h"

// 1496:000C: void fn1496_000C(Register Eq_14 ds, Stack Eq_14 ptrArg04, Stack Eq_14 wArg08)
// Called from:
//      fn0800_7DD1
//      fn0800_8095
void fn1496_000C(Eq_14 ds, Eq_14 ptrArg04, Eq_14 wArg08)
{
	Eq_14 cx_15 = wArg08;
	if (wArg08 == 0x00)
		return;
	if (Mem14[ds:0x38C0:word16] == 0x00)
	{
		Eq_14 dx_19 = Mem14[ds:0x38C2:word16];
		struct Eq_58267 * ds_74 = SLICE(ptrArg04, selector, 16);
		word16 Eq_58267::* si_22 = (word16) ptrArg04;
		do
		{
			__out<word16>(dx_19, ds_74->*si_22);
			++si_22;
			--cx_15;
		} while (cx_15 != 0x00);
	}
	else
	{
		selector es_44 = Mem43[ds:0x38C0:selector];
		Eq_14 di_45 = Mem43[ds:0x38C2:word16];
		struct Eq_58279 * ds_76 = SLICE(ptrArg04, selector, 16);
		word16 Eq_58279::* si_48 = (word16) ptrArg04;
		do
		{
			(es_44->*di_45.u5).t0000.u1 = ds_76->*si_48;
			++si_48;
			--cx_15;
		} while (cx_15 != 0x00);
	}
}

