// LOADW_1492.c
// Generated by decompiling LOADW.EXE
// using Reko decompiler version 0.12.2.0.

#include "LOADW.h"

// 1492:0008: void fn1492_0008(Register Eq_14 ds, Stack Eq_14 wArg04)
// Called from:
//      fn0800_0D60
void fn1492_0008(Eq_14 ds, Eq_14 wArg04)
{
	if (Mem7[ds:0x38C0:word16] == 0x00)
		__out<word16>(Mem7[ds:0x38C2:word16], wArg04);
	else
		Mem25[Mem22[ds:0x38C0:selector]:Mem22[ds:0x38C2:word16] + 0x00:word16] = wArg04;
}

