// LOADW_146C.c
// Generated by decompiling LOADW.EXE
// using Reko decompiler version 0.12.2.0.

#include "LOADW.h"

// 146C:0004: Register word16 fn146C_0004(Register byte ah, Register Eq_14 ds, Stack Eq_14 wArg04, Stack Eq_37792 ptrArg06, Stack Eq_14 ptrArg0A)
// Called from:
//      fn0800_83C5
word16 fn146C_0004(byte ah, Eq_14 ds, Eq_14 wArg04, Eq_37792 ptrArg06, Eq_14 ptrArg0A)
{
	struct Eq_57652 * es_35 = SLICE(ptrArg0A, selector, 16);
	cui16 Eq_57652::* di_36 = (word16) ptrArg0A;
	word16 cx_38;
	word16 dx_40;
	word16 bp_39;
	fn146C_0087(ptrArg06.u1->b0000, 0x00, 0x00, 0x00, di_36, es_35, out cx_38, out dx_40, out bp_39);
	word16 cx_49;
	word16 dx_51;
	word16 bp_50;
	fn146C_0087(ptrArg06.u1->b0002, cx_38, dx_40, bp_39, di_36, es_35, out cx_49, out dx_51, out bp_50);
	word16 cx_60;
	word16 dx_62;
	word16 bp_61;
	fn146C_0087((&ptrArg06.u1->b0000)[(uipr32) wArg04], cx_49, dx_51, bp_50, di_36, es_35, out cx_60, out dx_62, out bp_61);
	cu16 cx_71;
	cu16 dx_73;
	uint16 bp_72;
	fn146C_0087((&ptrArg06.u1->b0000)[(uipr32) &wArg04.u5->ptr0002], cx_60, dx_62, bp_61, di_36, es_35, out cx_71, out dx_73, out bp_72);
	byte cl_83 = (byte) cx_71;
	uint16 bx_101 = bp_72;
	uint16 dx_85 = dx_73 >> 0x02;
	byte dh_131 = SLICE(dx_73 >> 0x02, byte, 8);
	uint16 cx_86 = cx_71 >> 0x05;
	byte ch_127 = SLICE(cx_71 >> 0x05, byte, 8);
	uint16 cx_100;
	uint16 dx_130;
	uint16 bx_102;
	<unknown> Eq_57778::* fp;
	if ((cl_83 & 0x1F) != 0x02)
	{
		if ((cl_83 & 0x1F) <= 0x02)
			return 0x00;
		if ((cl_83 & 0x1F) != 0x04)
		{
			uint8 al_112 = bp_72 /u (cl_83 & 0x1F);
			cx_100 = SEQ(ch_127, (cx_71 >> 0x05) /u (cl_83 & 0x1F));
			dx_130 = SEQ(dh_131, (dx_73 >> 0x02) /u (cl_83 & 0x1F));
			bx_102 = SEQ(al_112, al_112);
			return fn146C_00AA(fp - 2, (byte) cx_100 & 0x1F, (byte) dx_130 & 0x1F, (byte) bx_102 & 0x1F, di_36, es_35, ds);
		}
	}
	else
	{
		dx_85 = dx_73 >> 0x02 << 0x01;
		cx_86 = cx_71 >> 0x05 << 0x01;
		bx_101 = bp_72 << 0x01;
	}
	dx_130 = dx_85 >> 0x02;
	cx_100 = cx_86 >> 0x02;
	bx_102 = bx_101 >> 0x02;
	return fn146C_00AA(fp - 2, (byte) cx_100 & 0x1F, (byte) dx_130 & 0x1F, (byte) bx_102 & 0x1F, di_36, es_35, ds);
}

// 146C:0087: Register byte fn146C_0087(Register uint8 al, Register word16 cx, Register word16 dx, Register word16 bp, Register (memptr (ptr16 Eq_57652) cui16) di, Register (ptr16 Eq_57652) es, Register out word16 cxOut, Register out word16 dxOut, Register out word16 bpOut)
// Called from:
//      fn146C_0004
byte fn146C_0087(uint8 al, word16 cx, word16 dx, word16 bp, cui16 Eq_57652::* di, struct Eq_57652 * es, word16 & cxOut, word16 & dxOut, word16 & bpOut)
{
	uint16 ax;
	al = (byte) ax;
	byte cl = (byte) cx;
	byte ch = SLICE(cx, byte, 8);
	uint16 bx_11 = (uint16) al;
	uint16 ax_34 = ax;
	word16 cx_25 = cx;
	if (bx_11 << 0x01 != 0x00)
	{
		cui16 ax_19 = (&(es->*di))[bx_11];
		ax_34 = (uint16) (SLICE(ax_19, byte, 8) & 0x7C);
		cx_25 = SEQ(ch, cl + 0x01) + (ax_19 & 992);
		dx += ax_34;
		bp += (uint16) ((byte) ax_19 & 0x1F);
	}
	cxOut = cx_25;
	dxOut = dx;
	bpOut = bp;
	return SLICE(ax_34, byte, 8);
}

// 146C:00AA: Register word16 fn146C_00AA(Sequence (ptr32 Eq_57771) ss_bp, Register byte cl, Register byte dl, Register byte bl, Register (memptr (ptr16 Eq_57652) cui16) di, Register (ptr16 Eq_57652) es, Register Eq_14 ds)
// Called from:
//      fn146C_0004
word16 fn146C_00AA(struct Eq_57771 * ss_bp, byte cl, byte dl, byte bl, cui16 Eq_57652::* di, struct Eq_57652 * es, Eq_14 ds)
{
	Mem7[ds:0x310A:byte] = bl;
	Mem9[ds:12552:byte] = dl;
	Mem11[ds:0x3109:byte] = cl;
	Mem12[ds:0x3106:word16] = 5000;
	word16 si_25 = 0x00;
	word16 cx_16 = ss_bp->w0010 - 0x01;
	word16 Eq_57652::* di_18 = di + 1;
	do
	{
		cu16 ax_23 = es->*di_18;
		bi8 al_41 = (SLICE(ax_23 >>u 0x05, byte, 0) & 0x1F) - Mem22[ds:0x3109:byte];
		bi8 bl_35 = (SLICE(ax_23, byte, 0) & 0x1F) - Mem22[ds:0x310A:byte];
		bi8 bh_37 = (SLICE(ax_23, byte, 8) >>u 0x02 & 0x1F) - Mem22[ds:12552:byte];
		++di_18;
		++si_25;
		int16 dx_49 = al_41 *s16 al_41 + bl_35 *s16 bl_35 + bh_37 *s16 bh_37;
		if (dx_49 == 0x00)
			return si_25;
		if (dx_49 <= Mem22[ds:0x3106:word16])
		{
			Mem55[ds:12555:word16] = si_25;
			Mem56[ds:0x3106:word16] = dx_49;
		}
		--cx_16;
	} while (cx_16 != 0x00);
	return Mem61[ds:12555:word16];
}

