// LOADW_147D.c
// Generated by decompiling LOADW.EXE
// using Reko decompiler version 0.12.2.0.

#include "LOADW.h"

// 147D:0000: Register byte fn147D_0000(Register Eq_14 ds)
// Called from:
//      main
byte fn147D_0000(Eq_14 ds)
{
	if (Mem0[ds:0x38C0:word16] == 0x00)
		return __in<byte>(Mem0[ds:0x3AC8:word16]);
	return Mem16[Mem16[ds:0x38C0:selector]:Mem16[ds:0x3AC8:word16] + 0x00:byte];
}

// 147D:001D: void fn147D_001D(Register Eq_14 ds, Stack Eq_14 bArg04)
// Called from:
//      main
void fn147D_001D(Eq_14 ds, Eq_14 bArg04)
{
	if (Mem7[ds:0x38C0:word16] == 0x00)
		__out<byte>(Mem7[ds:0x3AC8:word16], bArg04);
	else
		Mem25[Mem22[ds:0x38C0:selector]:Mem22[ds:0x3AC8:word16] + 0x00:byte] = bArg04;
}

