// LOADW_1463.c
// Generated by decompiling LOADW.EXE
// using Reko decompiler version 0.12.2.0.

#include "LOADW.h"

// 1463:000C: Register word16 fn1463_000C(Register Eq_14 ds)
// Called from:
//      fn0800_0000
//      fn0800_00A0
word16 fn1463_000C(Eq_14 ds)
{
	word16 ax_16 = 0x00;
	if (memcmp(*((word32) ds + 12542), *((word16) SLICE(msdos_get_interrupt_vector(0x67), selector, 16) + 0x0A), 0x08) != 0x00)
		ax_16 = ~0x00;
	return ax_16;
}

// 1463:0028: Register word16 fn1463_0028()
// Called from:
//      fn0800_00A0
//      fn1054_3721
word16 fn1463_0028()
{
	word16 dx_5;
	word16 bx_14;
	byte ah_6 = ems_get_number_of_pages(out bx_14, out dx_5);
	if (ah_6 != 0x00)
		bx_14 = SEQ(~0x00, ah_6);
	return bx_14;
}

// 1463:0037: Register word16 fn1463_0037(Stack Eq_14 wArg04)
// Called from:
//      fn0800_00A0
//      fn1054_3721
word16 fn1463_0037(Eq_14 wArg04)
{
	word16 dx_10;
	byte ah_11 = ems_get_handle_and_allocate_memory(wArg04, out dx_10);
	if (ah_11 != 0x00)
		dx_10 = SEQ(~0x00, ah_11);
	return dx_10;
}

// 1463:004E: void fn1463_004E(Stack word16 wArg04, Stack Eq_14 wArg06)
// Called from:
//      fn0800_0040
//      fn1054_3691
void fn1463_004E(word16 wArg04, Eq_14 wArg06)
{
	ems_map_memory(SLICE(wArg04, byte, 8), (uint16) (byte) wArg04, wArg06) == 0x00;
}

// 1463:006B: Register word16 fn1463_006B()
// Called from:
//      fn0800_00A0
//      fn1054_3721
word16 fn1463_006B()
{
	word16 bx_4;
	ems_get_page_frame_segment(out bx_4) == 0x00;
	return bx_4;
}

// 1463:007C: void fn1463_007C(Stack Eq_14 wArg04)
// Called from:
//      fn0800_0000
//      fn1054_39D9
void fn1463_007C(Eq_14 wArg04)
{
	ems_release_memory(wArg04) == 0x00;
}

