// LOADW.globals.c
// Generated by decompiling LOADW.EXE
// using Reko decompiler version 0.12.2.0.

#include "LOADW.h"

uint32 g_dw0200; // 00000200
uint32 g_dw021A; // 0000021A
uint32 g_dw1720; // 00001720
uint32 g_dw1728; // 00001728
uint32 g_dw172E; // 0000172E
uint32 g_dw1734; // 00001734
uint32 g_dw5B96; // 00005B96
uint32 g_dw5C9E; // 00005C9E
Eq_14 g_tADDCAFE0;
